---
output: github_document
---


# Machine Learning with R

### Course Description

Welcome to Machine Learning with R\! This short course provides a hands-on approach to applying machine learning techniques with the R programming language. In this course you will gain deeper knowledge around the machine learning process and apply various supervised machine learning algorithms. The following is an outline of the material covered in this training:

**Day 1**

| Topic                                 |     Time      |
| :------------------------------------ | :-----------: |
| [Getting started](https://koalaverse.github.io/AnalyticsSummit19/01-intro.html) |  8:30 - 9:15  |
| [Supervised modeling process](https://koalaverse.github.io/AnalyticsSummit19/02-supervised-modeling-process.html) | 9:30 - 10:30 |
| [Feature & target engineering](https://koalaverse.github.io/AnalyticsSummit19/03-engineering.html) |  10:45 - 11:45  |
| Lunch                                 | 12:00 - 1:00  |
| [Regression & cousins](https://koalaverse.github.io/AnalyticsSummit19/04-regression.html) |  1:00 - 2:30  |
| [Interpretable machine learning](https://bradleyboehmke.github.io/CinDay-RUG-IML-2018/slides-source.html#1) |  2:45 - 4:15  |
| Q\&A                                  |  4:15 - 5:00  |

**Day 2**

| Topic                                      |     Time      |
| :----------------------------------------- | :-----------: |
| Recap & morning discussion                    |  8:30 - 9:00  |
| [Tree-based methods](https://koalaverse.github.io/AnalyticsSummit19/09-Trees.html)  |  9:00 - 12:00 |
| Lunch                                        | 12:00 - 1:00  |
| [Support vector machines](https://koalaverse.github.io/AnalyticsSummit19/08-SVM.html) |  1:00 - 2:30  |
| [Stacked models & auto ML](https://koalaverse.github.io/AnalyticsSummit19/10-stacking.html)  |  2:45 - 3:15  |
| [Kaggle competition](https://www.kaggle.com/t/c58df800271e467b8e1bf5e9ca105b40) |  3:30 - 4:30  |
| Q\&A                                       |  4:30 - 5:00  |

___Schedule is still being refined and is subject to change; however, the topics should remain the same.___

### Course Preparation

To prepare for this course please complete the following ***prior*** to
the day of class:

1.  Download the student material [here](https://minhaskamal.github.io/DownGit/#/home?url=https://github.com/koalaverse/AnalyticsSummit19/tree/master/student-scripts).
    This will provide you with the R scripts and notebooks to follow along
    during class.
    
2.  After downloading the files, open the `00-run-this-script-first.R` and run
    the code.  This will make sure you have all required packages that will be
    used in the class.

3.  All slides are available via the hyperlinks in the schedule above so
    that you can follow along.

4.  Please have the following versions of R and RStudio installed. If
    you have an earlier version of R that is at least version 3.4.5 or
    later you should be ok but its best to be as current as possible.
    
      - R: 3.5.1 \[[download latest
        version](https://cran.r-project.org/)\]
      - RStudio: 1.1.463 \[[download latest
        version](https://www.rstudio.com/products/rstudio/download/#download)\]
        
5. This course makes ___strong___ assumptions about your prior knowledge such as
   your ability to define functions, manage R objects, control the flow of a program, 
   and other basic tasks. To ensure your success, be sure that you have reviewed 
   and are comfortable with the material covered in the [Intro to R](https://github.com/uc-r/Intro-R) 
   and [Intermediate R](https://github.com/uc-r/Intermediate-R) courses. 
   
If you have any specific questions prior to the class you can reach out to 
Brad Boehmke at [bradleyboehmke@gmail.com](mailto:bradleyboehmke@gmail.com) 
or Brandon Greenwell at [greenwell.brandon@gmail.com ](mailto:greenwell.brandon@gmail.com ).